// Concatenates the GLSL modules into a single self-contained JS file so the
// renderer can run from file:// (fetch() of .glsl would be blocked by CORS).
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

// HERO_SRC lets a parallel agent build from its own private copy of the
// shader tree, so concurrent builders never see each other's half-saved edits.
const SRC_DIR = process.env.HERO_SRC || join(here, 'src');
const BUNDLE  = process.env.HERO_BUNDLE || 'shaders';
const src  = (f) => readFileSync(join(SRC_DIR, f), 'utf8');

export const PIECES = [
  'p1_blade_form',
  'p2_blade_material',
  'p3_rot',
  'p4_guard',
  'p5_grip',
  'p6_pommel',
  'p7_lighting',
  'p8_presentation',
];

const VERSION = '#version 300 es\n';
const head    = src('core_head.glsl');
const pieces  = PIECES.map((p) => `\n// ===== ${p} =====\n` + src(`${p}.glsl`)).join('\n');

const scene       = src('core_scene.glsl');
const sceneFS     = VERSION + head + pieces + '\n' + scene + '\n' + src('core_main.glsl');
const compositeFS = VERSION + head + pieces + '\n' + scene + '\n' + src('core_composite.glsl');

// Line map so a compile error can be traced back to the owning module.
function lineMap(parts) {
  const map = [];
  let line = 1;
  for (const [name, text] of parts) {
    const n = text.split('\n').length;
    map.push({ name, from: line, to: line + n - 1 });
    line += n;
  }
  return map;
}
const sceneMap = lineMap([
  ['#version', VERSION],
  ['core_head', head],
  ...PIECES.map((p) => [p, `\n// ===== ${p} =====\n` + src(`${p}.glsl`)]),
  ['core_scene', '\n' + scene],
  ['core_main', '\n' + src('core_main.glsl')],
]);

const out = `// GENERATED by build.mjs — do not edit. Edit the .glsl sources instead.
window.SHADERS = {
  scene: ${JSON.stringify(sceneFS)},
  composite: ${JSON.stringify(compositeFS)},
  sceneMap: ${JSON.stringify(sceneMap)}
};
`;

writeFileSync(join(here, 'build', `${BUNDLE}.js`), out);
console.log(`built ${BUNDLE}.js from ${SRC_DIR} — scene ${sceneFS.split('\n').length} lines`);
